title: Build Meetup
baseURL: /
params:
  favicon: images/favicon.png
  logo_dark: images/logo.svg
  logo_light: images/logo-white.svg
  hamburger_background_image: /images/leaf-light-grey.svg
  bg_image_primary: /images/header.jpg
  bg_image_primary_opacity: 60
  bg_image_secondary: /images/leaf-light-grey.svg
  bg_image_product: /images/leaf.svg
  palette: green
  main_menu: []
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
